# Generated by Django 3.0 on 2020-11-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='libre',
            field=models.BooleanField(default=True),
        ),
    ]
